<html>
  <head>
     <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"> 
<h1>Izmjeni scenarij:</h1>
  </head>
  <body>
	 <ul class="list-group">
	 	<?php
	 	foreach ($this->filelist as $directoryLong) {
			$directory = basename($directoryLong);
	 		echo '<a href="'.dirname($_SERVER[REQUEST_URI])."/displayAddRemoveTemplatesToScenario?scenarioName=".$directory.'"><li class="list-group-item">'.$directory.'</li></a>';
	 	}
	 	?>
	</ul>
	</br>
	<a href="<?php echo dirname($_SERVER[REQUEST_URI]);?>">Home</a>
  </body>
</html>