<h2>Izrada novog scenarija:</h2>
<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php $fileElement = $form->get('scenario-name'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formText($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>

	</br>
	<a href="<?php echo dirname($_SERVER[REQUEST_URI]);?>">Home</a>