<html>
  <head>
     <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"> 
<h1>Successfully finished!</h1>
<h2>Download zip:</h2>
  </head>
  <body>
  <?php
	$first = dirname($_SERVER[REQUEST_URI]);
	$second = dirname($first);
	$third = dirname($second);
	$withFileRef = "$third/data/done/$this->scenario_name/$this->newDirectory";
var_dump($withFileRef);	
  ?>
	<a href="<?php echo $withFileRef;?>">test</a>
  <a href="<?php echo "data/done/".$this->scenario_name."/".$this->newDirectory;?>"><?= $this->newDirectory ?></a>
	</br>
	<a href="<?php echo dirname($_SERVER[REQUEST_URI]);?>">Home</a>
  </body>
</html>