
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Smart Wizard 2 - Ajax Contents Example - a javascript jQuery wizard control plugin</title>

<?php

use Zend\Session\Container;

echo $this->headLink()
	->prependStylesheet($this->basePath() . '/gemark-work/public/styles/demo_style.css')
	->prependStylesheet($this->basePath() . '/gemark-work/public/styles/smart_wizard_vertical.css');

echo $this->headScript()
        ->prependFile($this->basePath() . '/gemark-work/public/js/jquery.smartWizard.js')
        ->prependFile($this->basePath() . '/gemark-work/public/js/jquery-2.0.0.min.js');
?>

<script type="text/javascript">
    $(document).ready(function(){
    	// Smart Wizard    	
  		$('#wizard').smartWizard({contentURL:'<?php echo dirname($_SERVER[REQUEST_URI]).'/vrstaElaborataInput'; ?>',transitionEffect:'slideleft',onFinish:onFinishCallback});
      
      function onFinishCallback(){
        $('form').submit();
      }     
		});
</script>
</head>
<body>
<div class="demoHead">   
  <h2>Izrada elaborata</h2> 
</div>
<table align="center" border="0" cellpadding="0" cellspacing="0">
<tr><td>
  <?php
  $form = $this->form;
  $form->setAttribute('action',"./elaboratSubmitHandler");
  $form->prepare();
  echo $this->form()->openTag($form);
  

  //generate elaboratID and store it to session
  $t = microtime(true);
  $micro = sprintf("%06d",($t - floor($t)) * 1000000);
  $d = new \DateTime( date('Y-m-d H:i:s.'.$micro, $t) );
  $elaboratID = $d->format("YmdHisu"); // note at point on "u"

  $session = new Container('base');
  $session->offsetSet('elaboratID', $elaboratID);


 ?>
 <input type="text" name="elaboratID" id="elaboratID" style="display: none;" value="<?php echo $session->offsetGet('elaboratID', $elaboratID); ?>">
<!-- Smart Wizard -->
  		<div id="wizard" class="swMain" style="height: 500px !important;  position: relative;">
  			<ul>
  				<li><a href="#step-1">
                <label class="stepNumber">1</label>
                <span class="stepDesc">
                   <small>Vrsta elaborata i sastavni dijelovi</small>
                </span>
            </a></li>
  				<li><a href="#step-2">
                <label class="stepNumber">2</label>
                <span class="stepDesc">
                   <small>Ulazni podatci</small>
                </span>
            </a></li>
  				<li><a href="#step-3">
                <label class="stepNumber">3</label>
                <span class="stepDesc">
                   <small>Predmetne čestice</small>
                </span>                   
             </a></li>
  				<li><a href="#step-4">
                <label class="stepNumber">4</label>
                <span class="stepDesc">
                   <small>Susjedne čestice</small>
                </span>                   
            </a></li>
  			</ul>
  			<div id="step-1">	
            <h2 class="StepTitle">Step 1 Content</h2>
            <ul type="disk">
  				    <li>List 1</li>
  				    <li>List 2</li>
            </ul>
            <p>
			opis 1
            </p>
            <p>
            opis 2
            </p>
            <p>
            opis 3
            </p>          			
        </div>
  			<div id="step-2">
            <h2 class="StepTitle">Step 2 Content</h2>	
            <p>
			opis 4
            </p>
            <p>
			opis 5
            </p>
            <p>
			opis 6
            </p> 
            <p>
            opis 7
            </p>          
        </div>                      
  			<div id="step-3">
            <h2 class="StepTitle">Step 3 Content</h2>	
            <p>
			opis 8
            </p>
            <p>
            opis 9
            </p>               				          
        </div>
  			<div id="step-4">
            <h2 class="StepTitle">Step 4 Content</h2>	
            <p>
			opis 10
            </p>
            <p>
            opis 11
            </p>
            <p>
            opis 12
            </p>                			
        </div>
  		</div>
<!-- End SmartWizard Content -->

<?php echo $this->form()->closeTag(); ?>

</td></tr>
</table>
<div>
  <button>Home</button>
</div>	
</body>
</html>
