<html>
	<head>
	<script type="text/javascript">
    $(document).ready(function(){ 	
  		var el = document.getElementById('usernames');
		el.onchange = function(e){
			if (e.currentTarget.value === "elaborat-10") {
				document.getElementById('ostalo-ime-elaborata').style.display = 'block';
			} else {
				document.getElementById('ostalo-ime-elaborata').style.display = 'none';
			}
		};
		});
	</script>
	</head>
	<body>
		<table>
			<tr>
				<td style="padding-right: 4em; display: inline-block;">
					<div>
					<h2>Vrsta elaborata:</h2>
					<?php
					$form = $this->form;
					$form->prepare();
					
					echo $this->formRow($form->get('usernames'));
						echo "</br>";						
					echo $this->formRow($form->get('ostalo-ime-elaborata'));
					echo $this->formRow($form->get('sastavni-dijelovi'), null, null, 'template-file');
					?>
					</div>
				</td>
			</tr>
		</table>
	</body>
</html>


 
