<html>
	<head>
		<h2>Predmetni ulazni podatci</h2>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<script>
			$(document).ready(function() {
				//prevent strange characters in oznaka elaborata
			   $(function (){
			   	$(oznakaElaborata).keyup(function (){
			   		if (this.value.match(/[^a-zA-Z0-9 ]/g)){
			   			this.value = this.value.replace(/[^a-zA-Z0-9 ]/g, '');
			   		}
			    });
			   });
				//common
				var max_fields = 10,
					allCounters = {
					x: 1,
					x1: 1,
					x2: 1
				};

				//container 1
			    var wrapper         = $(".container1"),
			    	add_button      = $(".add_form_field");

			    //container2
			    var wrapper2         = $(".container2"),
			    	add_button2      = $(".add_form_field_2");

			    var createElementsOnClick =	function(counter, idParent, mainLabel, elWrapper) {
			        if(allCounters[counter] < max_fields){
			            allCounters[counter]++;
			            var el2 = document.getElementById(idParent + '1').cloneNode(true);
			            el2.id = idParent + allCounters[counter];
			            var inps = el2.getElementsByTagName('input');
			            for (var p = 0;p< inps.length; p++ ){
			            	inps[p].value = '';
			            	inps[p].id = inps[p].id.replace(/\d+/, allCounters[counter]);
			            	inps[p].name = inps[p].id;
			            }
			            el2.getElementsByTagName('h3')[0].innerText = mainLabel + allCounters[counter] + ":";
			            el2.getElementsByTagName('h3')[0].insertAdjacentHTML('afterend','<a class="delete" style="color: #ff8000; margin-left: 10px;"><i class="fa fa-trash"></i></a>');
			            $(elWrapper).append(el2); //add input box
			        } else {
					  	alert('You Reached the limits')
	  				}
			    }

				var createDynamicElements = function(elaboratData, arrIds, idParent, mainLabel, counter, elWrapper) {
				    var dynamicElements = {}
				    for (key in elaboratData) {
				    	var expr = arrIds[0],
				    		re = new RegExp('^' + expr + '\\d+');
					    if (key.match(re)) dynamicElements[key] = elaboratData[key];
					}
					var dynamicKeys = Object.keys(dynamicElements);
					for (var n = 0; n < dynamicKeys.length; n++) {
						var dbElementIndex = dynamicKeys[n].match(/\d+/)[0];
						if (n !== 0) {
							createElementsOnClick(counter, idParent, mainLabel, elWrapper);
						}

						for (var a = 0; a < arrIds.length; a++) {
					    	document.getElementById(arrIds[a] + allCounters[counter]).value = elaboratData[arrIds[a] + dbElementIndex];
					    }
					}
				}			
				var createElements = function(elaboratData) {
					if (elaboratData) {
						//gornji fiksni elementi
						document.getElementById("oznakaElaborata").value = elaboratData.oznakaElaborata;
						document.getElementById("podrucniUred").value = elaboratData.podrucniUred;
						document.getElementById("katastarskaOpcina").value = elaboratData.katastarskaOpcina;
						document.getElementById("brojLista").value = elaboratData.brojLista;
						document.getElementById("zemljiOpcina").value = elaboratData.zemljiOpcina;

						//kontakt fiksni elementi
						document.getElementById("kontaktOsoba").value = elaboratData.kontaktOsoba;
						document.getElementById("mjestoElaborata").value = elaboratData.mjestoElaborata;
						document.getElementById("datumElaborata").value = elaboratData.datumElaborata;

					    createDynamicElements(elaboratData, ['ime', 'prezime', 'OIB', 'adresa'], "narucitelj", "Naručitelj", 'x', wrapper);
					    createDynamicElements(elaboratData, ["dokumentNaziv","dokumentKlasa","dokumentUrbroj","dokumentIzdano","dokumentDatum"], "dokument", "Dokument", 'x2', wrapper2);
					}

				    //set elements on click
				    $(add_button).click(function(e){
				    	e.preventDefault();
				        createElementsOnClick('x', "narucitelj", "Naručitelj", wrapper);  
				    });			  
				    $(wrapper).on("click",".delete", function(e){
				        e.preventDefault(); $(this).parent('div').remove();
				    })

				    
				    $(add_button2).click(function(e){
				    	e.preventDefault();
				        createElementsOnClick('x2', "dokument", "Dokument", wrapper2);
				    });			  
				    $(wrapper2).on("click",".delete", function(e){
				        e.preventDefault(); $(this).parent('div').remove();
				    })
			}

			var elaboratIDFromUrl = window.location.search ? window.location.search.match(/elaboratID=(\d+)/)[1] : undefined;
	    	if (elaboratIDFromUrl) {
	    		$.ajax({
			        url: "./dohvatiElaborat?elaboratID=" + elaboratIDFromUrl, 
			        success: function(result){
			          createElements.call(this, JSON.parse(result));
			        }.bind(this)
		      	});
	    	} else {
	    		createElements.call(this);
	    	} 
			});
		</script>
	</head>
	<body>
		<table>
			<tr>
				<td>					
					<?php
					$form = $this->form;
					$form->prepare();						
					echo $this->formRow($form->get('oznakaElaborata'));
					?>
				</td>
			</tr>
			<tr>
				<td style="padding-right: 4em; display: inline-block;">
					<div style="float: left; width: 25%;">					
						<?php
						$form = $this->form;
						$form->prepare();						
						echo $this->formRow($form->get('podrucniUred'));
						?>
					</div>
					<div style="float: left; width: 25%;">					
						<?php
						$form = $this->form;
						$form->prepare();					
						echo $this->formRow($form->get('katastarskaOpcina'));
						?>
					</div>
					<div style="float: left; width: 25%;">					
						<?php
						$form = $this->form;
						$form->prepare();					
						echo $this->formRow($form->get('brojLista'));
						?>
					</div>
					<div style="float: left; width: 25%;">					
						<?php
						$form = $this->form;
						$form->prepare();					
						echo $this->formRow($form->get('zemljiOpcina'));
						?>
					</div>

					<div class="container1" style="margin-top: 25px; margin-right: 50px; float: left; width: 25%;">
						<button class="add_form_field">Dodaj naručitelja &nbsp;
							<span style="font-size:16px; font-weight:bold;">+ </span>
						</button>
						<div id=narucitelj1>
						<h3 style="display: inline-block;">Naručitelj 1:</h3>
							<?php
							$form = $this->form;
							$form->prepare();
							
							echo $this->formRow($form->get('ime1'));
								echo "</br>";						
							echo $this->formRow($form->get('prezime1'));
								echo "</br>";						
							echo $this->formRow($form->get('OIB1'));
								echo "</br>";						
							echo $this->formRow($form->get('adresa1'));
							?>
						</div>
					</div>


					<div class="container2" style="margin-top: 25px; margin-right: 50px; float: left; width: 25%;">
						<button class="add_form_field_2">Dodaj dokument &nbsp;
							<span style="font-size:16px; font-weight:bold;">+ </span>
						</button>
						<div id=dokument1>
						<h3 style="display: inline-block;">Dokument 1:</h3>
							<?php
							$form = $this->form;
							$form->prepare();
							
							echo $this->formRow($form->get('dokumentNaziv1'));
								echo "</br>";						
							echo $this->formRow($form->get('dokumentKlasa1'));
								echo "</br>";						
							echo $this->formRow($form->get('dokumentUrbroj1'));
								echo "</br>";						
							echo $this->formRow($form->get('dokumentIzdano1'));
								echo "</br>";						
							echo $this->formRow($form->get('dokumentDatum1'));
							?>
						</div>
					</div>

					<div class="container4" style="margin-top: 25px; margin-right: 50px; float: left; width: 25%;">
						<div id=informacije1>
						<h3 style="display: inline-block; margin-top: 26%;">Informacije:</h3>
							<?php
							$form = $this->form;
							$form->prepare();
							
							echo $this->formRow($form->get('kontaktOsoba'));
								echo "</br>";
							echo $this->formRow($form->get('mjestoElaborata'));
								echo "</br>";
							echo $this->formRow($form->get('datumElaborata'));
							?>
						</div>
					</div>
				</td>
			</tr>
		</table>
	</body>
</html>


 
