<html>
	<head>
		<h2>Predmetne čestice, nositelji i omeđenja</h2>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<script>
			$(document).ready(function() {				
			    var max_fields31     = 10,
			    	wrapper31         = $(".container31"),
			    	add_button31      = $(".add_form_field_31"),		  
			    	x31 = 1,
			    	arrOfCounters = [1];	

				var createNositeljiOnClick = function(parentBrCestice, childValue) {
			    	var brCestice = parentBrCestice.getAttribute('brcestice'),
	            		newNositelj = document.getElementById("predNositeljPrava-1-1").cloneNode(true),
	            		brNositelja;

	            	arrOfCounters[brCestice-1]++;
	            	brNositelja = arrOfCounters[brCestice-1];
	            	newNositelj.id = 'predNositeljPrava-' + brCestice + '-' + brNositelja;
	            	newNositelj.name = newNositelj.id;
	            	newNositelj.placeholder = newNositelj.placeholder.replace(/\d+/, brNositelja);
	            	newNositelj.value = childValue;

	            	parentBrCestice.parentElement.appendChild(newNositelj);
			    }

		    	var createElementsOnClick = function() {
		    		if(x31 < max_fields31){
			            x31++;
			            var el2 = document.getElementById("brojKatCesParent1").cloneNode(true);
			            el2.id = 'brojKatCesParent' + x31;
			            var inps = el2.getElementsByTagName('input');
			            for (var p = 0;p< inps.length; p++ ){
			            	if (p > 1) {
			            		inps[p].className = 'toRemove';
			            	} else {
			            		inps[p].value = '';
				            	inps[p].id = inps[p].id.replace(/\d+/, x31);
				            	inps[p].name = inps[p].id;
			            	}			            	
			            }
			            var listToRemove = el2.getElementsByClassName('toRemove');
			            while(listToRemove.length > 0){
					        listToRemove[0].remove();
					    }
			            arrOfCounters.push(1);
			            var btnDodajNositelja = el2.getElementsByTagName('button')[0];
			            btnDodajNositelja.id = btnDodajNositelja.id.replace(/\d+/, x31);
			            btnDodajNositelja.setAttribute('brcestice',x31);
			            btnDodajNositelja.onclick = function(e) {
			            	var brCestice = e.target.getAttribute('brcestice'),
			            		newNositelj = document.getElementById("predNositeljPrava-1-1").cloneNode(true),
			            		brNositelja;

			            	arrOfCounters[brCestice-1]++;
			            	brNositelja = arrOfCounters[brCestice-1];
			            	newNositelj.id = 'predNositeljPrava-' + brCestice + '-' + brNositelja;
			            	newNositelj.name = newNositelj.id;
			            	newNositelj.placeholder = newNositelj.placeholder.replace(/\d+/, brNositelja);

			            	e.target.parentElement.appendChild(newNositelj);
			            };
			            el2.getElementsByTagName('h3')[0].innerText = "Čestica " + x31 + ":";
			            el2.getElementsByTagName('h3')[0].insertAdjacentHTML('afterend','<a class="delete" style="color: #ff8000; margin-left: 10px;"><i class="fa fa-trash"></i></a>');
			            $(wrapper31).append(el2); //add input box
			        } else {
				  		alert('You Reached the limits')
				  	}
		    	}

			    var createDynamicElements = function(elaboratData) {
			    	var dynamicElements = {}
			    	//uzmi sve elemente 'broj cestice'
				    for (key in elaboratData) {
				    	var expr = "brojKatCes",
				    		re = new RegExp('^' + expr + '\\d+');
					    if (key.match(re)) dynamicElements[key] = elaboratData[key];
					}
					var dynamicKeys = Object.keys(dynamicElements);
					for (var n = 0; n < dynamicKeys.length; n++) {
						var dbElementIndex = dynamicKeys[n].match(/\d+/)[0];
						if (n !== 0) {
							createElementsOnClick();
						}

						var createdBrCestica = document.getElementById("brojKatCes" + x31);
						createdBrCestica.value = elaboratData["brojKatCes" + dbElementIndex];

						var childDynamicElements = {}
						for (childKey in elaboratData) {
					    	var childExpr = "predNositeljPrava-" + dbElementIndex + '-',
					    		reChild = new RegExp('^' + childExpr + '\\d+');
						    if (childKey.match(reChild)) childDynamicElements[childKey] = elaboratData[childKey];
						}
						
						var dynamicChildKeys = Object.keys(childDynamicElements);
			            for (var c = 0; c < dynamicChildKeys.length; c++) {
			            	document.getElementById('predNositeljPrava-' + x31 + '-1').value = elaboratData[dynamicChildKeys[0]];
			            	if (c !== 0) {
			            		createNositeljiOnClick(createdBrCestica, elaboratData[dynamicChildKeys[c]]);
			            	}

			            }
					}
				}			

				var createElements = function(elaboratData){
				    if (elaboratData) {
				    	document.getElementById("cesticaOmedenja").value = elaboratData.cesticaOmedenja;
				    	createDynamicElements(elaboratData);
				    }

				    $(add_button31).click(function(e){
				        e.preventDefault();
				        if(x31 < max_fields31){
				            x31++;
				            var el2 = document.getElementById("brojKatCesParent1").cloneNode(true);
				            el2.id = 'brojKatCesParent' + x31;
				            var inps = el2.getElementsByTagName('input');
				            for (var p = 0;p< inps.length; p++ ){
				            	if (p > 1) {
				            		inps[p].className = 'toRemove';
				            	} else {
				            		inps[p].value = '';
					            	inps[p].id = inps[p].id.replace(/\d+/, x31);
					            	inps[p].name = inps[p].id;
				            	}			            	
				            }
				            var listToRemove = el2.getElementsByClassName('toRemove');
				            while(listToRemove.length > 0){
						        listToRemove[0].remove();
						    }
				            arrOfCounters.push(1);
				            var btnDodajNositelja = el2.getElementsByTagName('button')[0];
				            btnDodajNositelja.id = btnDodajNositelja.id.replace(/\d+/, x31);
				            btnDodajNositelja.setAttribute('brcestice',x31);
				            btnDodajNositelja.onclick = function(e) {
				            	var brCestice = e.target.getAttribute('brcestice'),
				            		newNositelj = document.getElementById("predNositeljPrava-1-1").cloneNode(true),
				            		brNositelja;

				            	arrOfCounters[brCestice-1]++;
				            	brNositelja = arrOfCounters[brCestice-1];
				            	newNositelj.id = 'predNositeljPrava-' + brCestice + '-' + brNositelja;
				            	newNositelj.name = newNositelj.id;
				            	newNositelj.placeholder = newNositelj.placeholder.replace(/\d+/, brNositelja);

				            	e.target.parentElement.appendChild(newNositelj);
				            };
				            el2.getElementsByTagName('h3')[0].innerText = "Čestica " + x31 + ":";
				            el2.getElementsByTagName('h3')[0].insertAdjacentHTML('afterend','<a class="delete" style="color: #ff8000; margin-left: 10px;"><i class="fa fa-trash"></i></a>');
				            $(wrapper31).append(el2); //add input box
				        } else {
					  		alert('You Reached the limits')
					  	}
				    });			  
				    $(wrapper31).on("click",".delete", function(e){
				        e.preventDefault(); $(this).parent('div').remove();
				    })

				  	$(dodajPredNosPrava1).click(function(e){
					    var brCestice = 1,
		            		newNositelj = document.getElementById("predNositeljPrava-1-1").cloneNode(true),
		            		brNositelja;

		            	arrOfCounters[brCestice-1]++;
		            	brNositelja = arrOfCounters[brCestice-1];
		            	newNositelj.id = 'predNositeljPrava-' + brCestice + '-' + brNositelja;
				        newNositelj.name = newNositelj.id;
		            	newNositelj.placeholder = newNositelj.placeholder.replace(/\d+/, brNositelja);

		            	e.target.parentElement.appendChild(newNositelj);
				  	})
				}

				var elaboratIDFromUrl = window.location.search ? window.location.search.match(/elaboratID=(\d+)/)[1] : undefined;
		    	if (elaboratIDFromUrl) {
		    		$.ajax({
				        url: "./dohvatiElaborat?elaboratID=" + elaboratIDFromUrl, 
				        success: function(result){
				          createElements.call(this, JSON.parse(result));
				        }.bind(this)
			      	});
		    	} else {
		    		createElements.call(this);
		    	} 
			});
		</script>
	</head>
	<body>
		<table>
			<tr>
				<td style="display: inline-block;">
					<div class="container31" style="margin-top: 25px; float: left; width: 80%;">
						<button class="add_form_field_31">Dodaj česticu &nbsp;
							<span style="font-size:16px; font-weight:bold;">+ </span>
						</button>
						<div id=brojKatCesParent1>
						<h3 style="display: inline-block;">Čestica 1:</h3>
							<?php
							$form = $this->form;
							$form->prepare();
							
							echo "</br>".$this->formRow($form->get('brojKatCes1'));
								echo "</br>";
							echo $this->formRow($form->get('predNositeljPrava-1-1'));
							echo '<button id="dodajPredNosPrava1" type="button" style="margin-left:  10px; display: inline-block;">+</button>';
								echo "</br>";
							//echo $this->formRow($form->get('predNositeljPravaDva1'));
							//	echo "</br>";
							//echo $this->formRow($form->get('predNositeljPravaTri1'));
							?>
						</div>
					</div>
						<?php
							echo $this->formRow($form->get('cesticaOmedenja'));
						?>
				</td>
			</tr>
		</table>
	</body>
</html>


 
